#
# These functions are based on those developed for fineSTRUCTURE
# http://www2.maths.bris.ac.uk/~madjl/finestructure/finestructureR.html
#

MakeColorYRP<-function(colby=0.05,final=NULL){
## makes yellow/red/purple colour scheme, adding rgb(final) if not null
	tmp<-c(rgb(1,seq(1,0,-colby),0),rgb(1,0,seq(colby,1,colby)),rgb(seq(1-colby,0,-colby),0,1.0))
	if(is.null(final)) return(tmp)
	c(tmp,rgb(final[1],final[2],final[3]))
}

plotHeatmap<-function(tmpmat,
		layoutf=0.2,# proportion of the plot to be used by the scale
		cols=NULL,# colour scale. Will be generated by MakeColors if NULL
		dend=NULL, # optional dendrogram to be placed at the top
		optpts=NULL, # optional points to add, e.g. MAP state
		labmargin=8, # margin for x,y labels
		layoutd=0.2, # proportion of the plot to be used by the dendrogram
		cex.axis=0.5, # cex.axis applies to the x,y labels
		crt=0, # character rotation of x,y labels (x is rotated the opposite direction)
		colscale=NULL, # specify a colour scale (default: ???)
		text.col=NULL, # colour of the labels (can be a vector, is recycled
		ignorebelow=0, # if text.col=0, then we white out everything below ignorebelow
		nodePar=list(cex=0,lab.cex=0.5,las=2),# nodePar as seen by plot.dendrogram
		edgePar=list(p.lwd=0,t.srt=0,t.off=0.2),# edgePar as seen by plot.dendrogram
		dendmar=c(0,0,2,1), # additional modification to the margins of the dendrogram
		scalemar=c(2,5,2,1), # additional modification to the margins of the scale
		hmmar=c(0,0,0,1), # additional modification to the margins of the heatmap
		cex.scale=1, # size of the characters in the scale
		scalelocs=NULL, # optional firced positions of the scale
		scalenum=10, # if scalelocs=NULL, the number of points to label on the scale
		scalesignif=3, # number of significant digits on scale
		scalelabel="", # label for the scale
		optcex=1.0, # size of the optional points
		optpch=20, # pch for the optional points
		optcol="white", # colour for the optional points
		labelsoff=c(1,1), # "margin" like, distance from colour/rotated labels and the axis
		max_colscale="",
    min_colscale="",
		main="",
		colby=0.05,
    ordering_flag=F,
		tickmarks=1) # size of tickmarks when using colour/rotated labels
{
  layout(matrix(c(1,2), 1, 2, byrow=TRUE),widths=c(1-layoutf,layoutf))
  
  if (ordering_flag) {
    cols<-c(
      rev(rgb(0,seq(1,0,-colby),1.0)),   # reverse lightblue,...,blue (255,0,0 => 0,255,255)
    	#rgb(1,0,seq(colby,1,colby)),      # red,...,purple (255,0,0   => 255,0,255)
      "#B1FFFF","#DEFFFF","#F3FFFF",     # from deep to light
      "#FFFFFF",
      "#FFFFCE","#FFFFA9","#FFFF63",     # from light to deep
      rev(rgb(1,seq(0,1,colby),0))       # reverse red,...,yellow (255,0,0 => 255,255,0)
    )
  } else {
    cols<-MakeColorYRP()
    #function(colby=0.05,final=NULL){
    ### makes yellow/red/purple colour scheme, adding rgb(final) if not null
    #	tmp<-c(
    #		rgb(1,seq(1,0,-colby),0),
    #		rgb(1,0,seq(colby,1,colby)),
    #		rgb(seq(1-colby,0,-colby),0,1.0)
    #	)
    #	if(is.null(final)) return(tmp)
    #	c(tmp,rgb(final[1],final[2],final[3]))
    #}
  }
  
  if (max_colscale == "") {
    max_colscale <- max(tmpmat,na.rm=T)
  } 
  
  if (ordering_flag) {
    colscale[1] <- min_colscale
    colscale[2] <- max_colscale
#     colscale<-c(max(ignorebelow,min(tmpmat[tmpmat>ignorebelow],na.rm=T),na.rm=T),max_colscale)
#     if (abs(colscale[1])<colscale[2]) {
#       colscale[1] = -1*colscale[2]
#     } else {
#       colscale[2] = -1*colscale[1]
#     }
  } else {
    colscale<-c(max(ignorebelow,min(tmpmat[tmpmat>ignorebelow],na.rm=T),na.rm=T),max_colscale)
  }
  

  ## BOTTOM LEFT: MAIN HEATMAP
  #par(mar=c(labmargin,labmargin,1,1)+hmmar)

  image(1:dim(tmpmat)[1],1:dim(tmpmat)[2],tmpmat,xaxt="n",yaxt="n",xlab="",ylab="",col=cols,zlim=colscale)
  
  labelsatx<-seq(1:dim(tmpmat)[2]) 
  labelsaty<-labelsatx
  
  axis(1,at=labelsatx,labels=dimnames(tmpmat)[[1]],las=2,cex.axis=cex.axis)
  axis(2,at=labelsaty,labels=dimnames(tmpmat)[[1]],las=2,cex.axis=cex.axis)

  ## BOTTOM RIGHT: SCALE
  #par(mar=c(labmargin,0,0,0)+scalemar) 
  colindex<-t(matrix(seq(min(colscale),max(colscale),length.out=100),ncol=1,nrow=100)) # colour scale
  image(1,1:100,colindex,xaxt="n",yaxt="n",xlab="",ylab="",col=cols,zlim=range(colindex), main=main)

  scalelocs <- min(colindex)+(max(colindex)-min(colindex))*seq(0,1,length.out=scalenum)
  scalephysicalpos <- seq(1,100,length.out=scalenum)
  axis(2,at=scalephysicalpos,labels=signif(scalelocs,scalesignif),las=2,cex.axis=cex.scale)
}
